---
title: "ESM 244 Lab Week 2"
author: "Michelle Shteyn"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)


# For PCA
library(ggfortify)


# For ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

#To make compound figures
library(patchwork)
```


## Part 1: PCA with penguins

Used axis rotation to create principal components, which are linear combinations of the original variables.
```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  scale() %>% 
  prcomp()

penguin_pca$rotation

#Have to make a dataset where the observations that exist match the obs that were used to create the PCA biplot, but still contain the other variables. Those are good to have because we can use other variables to update the aesthetics of the autoplot.
penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

#autoplot recognizes the type of data I am giving this, and assumes the type of output I want to create
autoplot(penguin_pca,
         data = penguin_complete, 
         colour = 'species',
         loadings=TRUE,
         loadings.label=TRUE)+
  theme_minimal()
```
We have 88% of the data captured in this PCA biplot.
































